make checksum optional in GDriveFileSystem
iterative/PyDrive2 pull request #195
Opened 2022-07-14 20:45 UTC by simone-viozzi

As discussed in #191, to make `GDriveFileSystem` compatible with google docs / sheet files the checksum in the metadata need to be optional.

I tried to run the tests in `test_fs.py` and it's all green.

2022-07-14 21:24 UTC, shcheklein commented
@efiop could someone familiar with DVC / fsspec check this please? That it does't break anything downstream (especially something from the fsspec perspective?). That would be really helpful.

@simone-viozzi thanks for the PR! looks like you need to run linters / pre-commit. Checks are failing.

2022-07-14 21:24 UTC, shcheklein requested changes
Check the linters please

2022-07-15 20:33 UTC, efiop commented on pydrive2/fs/spec.py
> +            )
```suggestion
            metadata["checksum"] = gdrive_file.get("md5Checksum")
```
same below

2022-07-15 20:35 UTC, efiop commented on pydrive2/fs/spec.py
> +            )
I guess same below.

2022-07-15 20:39 UTC, efiop commented
> @efiop could someone familiar with DVC / fsspec check this please? That it does't break anything downstream (especially something from the fsspec perspective?). That would be really helpful.

Using `None` is fine, doesn't look like we are using the checksum anywhere anyway (at least yet).

2022-07-15 20:41 UTC, efiop commented
Oh, looks like we haven't had PRs created from forks in awhile and the CI is failing due to abscent credentials 🙁 I guess this should be pretty safe to merge as is for now (with review addressed).

2022-07-15 21:04 UTC, shcheklein commented
> Oh, looks like we haven't had PRs created from forks in awhile and the CI is failing due to abscent credentials 🙁

Need to change the GH action (I'll do this). Going to use `pull_request_target` with the environments, not sure if it's the way that we use now in the DVC projects.

Thanks, @efiop !

2022-07-15 21:42 UTC, efiop approved these changes

2022-07-15 22:17 UTC, efiop commented
Nice catch! Thank you, @simone-viozzi !

2022-07-15 22:18 UTC, merged